PREFIX schema: <http://schema.org/>

select * where {
    {
        values ?event {<https://www.lavitrineduquebec.com/activity/Femme_s_#Event>}
        filter NOT EXISTS { ?event schema:subEvent ?subEvent }
    }
    UNION 
    {
        <https://www.lavitrineduquebec.com/activity/Femme_s_#Event>  schema:subEvent ?event .
    }
    OPTIONAL {
        ?event schema:startDate ?startDate .
    }   
    OPTIONAL {
        ?event schema:url ?webpage .
    }   
    OPTIONAL {
        ?event schema:offers/schema:url ?offer_url 
    }  
} limit 100